spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=forex
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwk-set-url: https://www.googleapis.com/oauth2/v2/certs